export const CATALOG_SEARCH_FIELD_CHANGE = 'CATALOG_SEARCH_FIELD_CHANGE'
export const CATALOG_SEARCH_REQUEST = 'CATALOG_SEARCH_REQUEST'
export const CATALOG_SEARCH_ERROR = 'CATALOG_SEARCH_ERROR'
export const CATALOG_SEARCH_SUCCESS = 'CATALOG_SEARCH_SUCCESS'